### ISSUE TITLE
Cannot export Foreman preset from Factorio

### ISSUE THREAD

**Issue by TheFieryFalcon** [DanielKote/Foreman2#61]
Every time I try, it just gives me this error:
"Could not copy Foreman export mod files to mod folder. Reinstall Foreman?" even though the foremanexport mod is already within my mods folder.

**Comment by DanielKote** [comment]
I believe this can happen if you have installed factorio in a restricted folder (ex: in your program files) where foreman is simply not allowed access to by windows. You can either try to run foreman as an administrator or if that doesnt work try to copy-paste your factorio folder to a different directory (ex: into your documents or desktop) and try exporting from there.
If neither of those options work out I will see what I can do.

**Comment by TheFieryFalcon** [comment]
Doesnt work, even when I unchecked this option on the folder
![image](https://user-images.githubusercontent.com/72846259/231412438-fa665f87-704d-48a4-a0af-bad91e1a1206.png)

**Comment by TheFieryFalcon** [comment]
Ok, I see the issue now. The mods folder is readonly as well, and whenever I try to change it, it just changes back.

**Comment by DanielKote** [comment]
So depending on if you are using steam or not:

Steam: navigate to settings -> downloads -> steam library folders. This will open up your storage manager where you can create a new steam library location (somewhere outside the protected folders such as any 'program files', 'windows', etc. - you can also just create a new folder like c:/steam library/ and use that). Then you can move/reinstall your steam factorio to the new library location which will hopefully not be protected.

Factorio.com: go to downloads and grab yourself a new full-game-for-windows-zip-package. Unzip it to a new (non-protected) location, copy your mods & saves from the other install directory, start the game, log in, ensure your game works fine, exit.

After this you should be able to use the new directory for your import via foreman. Alternatively you can use one of the existing presets, but thats very limiting as it doesnt take into account your specific set of mods.

**Comment by TheFieryFalcon** [comment]
No, the problem is even after I've copied and pasted the folder to another location it still remains readonly and cannot be changed.

**Comment by DanielKote** [comment]
Ok, so I tried to force this error by both making everything in a factorio folder read only along with moving the factorio install into my program files. In the first case the import completed as expected, in the second case factorio wouldnt even start due to it not having enough privileges to create its lock file.
Could you try the import again and then attach the errorlog.txt file (in the foreman app folder) to a comment here? That might clear some things up.

**Comment by TheFieryFalcon** [comment]
[errorlog.txt](https://github.com/DanielKote/Foreman2/files/11260640/errorlog.txt)

**Comment by DanielKote** [comment]
Did you manually move the mods from the 'mod' folder from foreman to your factorio mods folder? Because you arent supposed to do that - foreman will take care of everything. The error you are experiencing is because the presets importer is trying to copy the export mods to the factorio mods folder and isnt finding them where they are supposed to be (and thus is correctly asking you to reinstall foreman to fix the issue).

I would recommend re-downloading foreman (zip), unzipping it, opening it, and running the import. Dont move/delete anything in the foreman folder and dont move the mods in the mod folder into your factorio mods folder - foreman preset importer is responsible for copying the mods to your factorio-mods directory, enabling them, running factorio in the background, and removing the mods at the end of import.

**Comment by TheFieryFalcon** [comment]
No, as you can see, the mods are still in the folders they are supposed to be in
![image](https://user-images.githubusercontent.com/72846259/233001068-d4cc2d6c-a979-4757-b5d8-80734b1916b1.png)

**Comment by DanielKote** [comment]
This is getting more and more peculiar... Could you please do the following:

1. Re-download foreman 2 from [here](https://github.com/DanielKote/Foreman2/releases/tag/v2.0-dev.13alpha).
2. Extract it to C:/Release/
3. Download factorio from their website (zip version) [here](https://www.factorio.com/get-download/1.1.80/alpha/win64-manual).
4. Extract it to C:/factorio/
5. Run factorio from c:/factorio, log in with your account, start a new game to ensure everything works as expected.
6. If you cant do steps 3-5, just skip them and use your currently installed factorio instead, though ideally deactivate all mods.
7. Run foreman and try to import the preset from the new factorio install.
8. zip up the c:/Release folder and upload it to google drive / dropbox / etc. and post the link.

I will then download that zip and see if maybe there is something weird going on.
Oh, and - which OS are you trying this on? Win 10 or Win 11 or other? Ive honestly only tested this on Win 10 so there might be some incompatibility with Win 11 that I would need to look into...

**Comment by TheFieryFalcon** [comment]
Huh... It seems to work with this configuration. Also, yes, I am using Windows 11.

**Comment by TheFieryFalcon** [comment]
I believe the problem is that I have two Release folders embedded inside each other, causing Foreman to become confused as to where the mod folders are. Thanks for your help!
