### ISSUE TITLE
Unsupported Pyanodon T.U.R.D.'s alternative recipes

### ISSUE THREAD

**Issue by JeromeJ** [DanielKote/Foreman2#64]
Hello, 

Pyanodon has T.U.R.D which allows to permanently overwrite some recipes and/or building's stats (speed, electricity consumption, pollution) but I don't see the overwritten recipes suggested/available in Foreman2 so everything is accurate until I enable some T.U.R.D. research then all is thrown off and inaccurate and afaik, there are no way to manually edit recipes. (Not through the interface at least, from what I've seen).

eg. if I enable the Internal Burner upgrade for Fastwood forestries, this recipe changes from:
![image](https://github.com/DanielKote/Foreman2/assets/650065/ac9c9934-f8a9-441a-b492-e6f3276e3456)
to
![image](https://github.com/DanielKote/Foreman2/assets/650065/f0afc4c3-bdd0-487a-946f-c33b23dd9b89)

And the building is faster and consume less electricity:
![image](https://github.com/DanielKote/Foreman2/assets/650065/a1027fa5-4c2b-4e31-ae92-6900b7459f6b)

**Comment by mrozpara** [comment]
There are two options (as for now):
1. go to settings => graph options => show unavailable items (DEV) - it will allow to see TURD recipes but marked as "unavailable". But you will also see some more recipes...
2. go pjson file with your preset and manually change Disabled/Enabled for given recipe

**Comment by JeromeJ** [comment]
> There are two options (as for now):
> 
> 1. go to settings => graph options => show unavailable items (DEV) - it will allow to see TURD recipes but marked as "unavailable". But you will also see some more recipes...
> 2. go pjson file with your preset and manually change Disabled/Enabled for given recipe

Mh, I tried both but it didn't work.

I checked in-game and the recipes' name are `log3` and `log3-cheap`.

When I enabled the Show unavaible items (DEV), that recipe still didn't appear (even after closing/re-opening).

Regarding the pjson file, do you mean my saved flowchart.json?
It did not contain the recipe log3-cheap and even upon adding it to the EnabledRecipes list, it still didn't show up.

If you meant the Presets/pyanodon.pjson file, it does not contain the recipe either and it looked less straight forward to manually add it.

**Comment by DanielKote** [comment]
Ok, so the issue here is that Py is making heavy use of disabled (and hidden / unavailable) recipes that are set to an assembler in realtime. This is unfortunately impossible to track as the changes are applied via lua script as you play the game.
In order to allow for these recipes you need to do the following (mrozpara covered most of it already):

1. go to settings => graph options => show unavailable items (DEV) - this will allow you to see the items & recipes that are never researched in a regular gameplay (or in this case recipes that are set via script during gameplay)
2. when you click on the add recipe button there should be a checkbox for 'show disabled' which will now show the unavailable & disabled recipes in the list (with their background colored red to denote them as disabled).

Alternatively to number 2 you can go into settings => enabled objects, switch the tab to recipes, search for the recipes you wish to use (in this example 'log') and select the checkmark 'show unavailables' (which will have a red background). You can then enable them here in order to get them to show up in the recipe selection without the 'show disabled' check (you still need number 1 though). If you do this instead of number 2 then these recipes will show up with a purple background instead to denote them as unavailable (but enabled)

Keep in mind that you will most likely need to refer back and forth between factorio and foreman to confirm which recipe you wish to use as there is no indication within foreman (outside of 'unavailable status') to denote which recipes are regular and which are TURD recipes.

**Comment by JeromeJ** [comment]
I had to re-import the preset for it to work! But now I can see them!

For TURD's tweaked buildings stats (see Internal burner on my 3rd screenshot), it's actually a hidden module so I've to go to settings to enable it if I wish to see it and be able to add it!
If I'm not mistaken, the TURD's "module" do not count towards the max module count. Eg. for Py's fast wood forestry, which is limited to 20 modules, I believe that, in game, you can still have 20 modules and the Internal burner is automatically added, hidden and does not count towards the 20.
So this might be a limitation in Foreman. Maybe I can open another issue?

**Comment by DanielKote** [comment]
TURD's module is made using a hidden beacon that is placed by the lua code (though I have no idea how the 'ashes as byproduct' is handled).
Unfortunately when I made the design for foreman I assumed only a single type of beacon would be used, so while you can enable the 'hidden beacon' and add it to the building (and enable the hidden modules as well), you cant at the moment use it together with actual beacons.
I am going to have to think about this, but for now I think adding a new issue 'use of multiple different beacons not supported' or something along those lines would be in order. Going to be honest with you - not sure when I will have time to work on this; its a pretty big change from the way things are handled and requires quite a bit of work (especially on the GUI side of things).
