### ISSUE TITLE
I can't import my mod list

### ISSUE THREAD

**Issue by jame2312** [DanielKote/Foreman2#66]
I may just be doing something wrong but here is the mods list. 
 let me know if I'm doing something wrong or if it's a bug. 
 FNEI = "0.4.1",
  Krastorio2 = "1.3.19",
  Krastorio2Assets = "1.2.1",
  LTN_Combinator_Modernized = "2.0.6",
  LTN_Content_Reader = "1.0.3",
  LogisticTrainNetwork = "1.18.3",
  LtnManager = "0.4.23",
  Milestones = "1.3.18",
  ModuleInserter = "5.2.4",
  RateCalculator = "3.1.2",
  SE_liquid_reactor = "1.0.2",
  SE_smooth_ship_walls = "1.0.0",
  ["Todo-List"] = "19.3.0",
  VehicleSnap = "1.18.5",
  ["aai-containers"] = "0.2.11",
  ["aai-industry"] = "0.5.20",
  ["aai-signal-transmission"] = "0.4.7",
  ["aai-vehicles-flame-tumbler"] = "0.6.1",
  ["alien-biomes"] = "0.6.8",
  base = "1.1.82",
  ["bullet-trails"] = "0.6.2",
  clock = "1.1.0",
  ["combat-mechanics-overhaul"] = "0.6.24",
  ["factorio-codex"] = "0.0.20",
  factoryplanner = "1.1.66",
  ["fireproof-bots"] = "1.1.3",
  flib = "0.12.8",
  ["grappling-gun"] = "0.3.3",
  informatron = "0.3.4",
  jetpack = "0.3.12",
  ["nixie-tubes"] = "1.1.3",
  pushbutton = "1.1.1",
  resourceMarker = "0.7.29",
  robot_attrition = "0.5.15",
  ["rocket-log"] = "1.1.11",
  ["se-ltn-glue"] = "0.6.0",
  ["se-space-trains"] = "0.1.12",
  ["shield-projector"] = "0.1.6",
  simhelper = "1.1.4",
  ["solar-calc"] = "0.3.11",
  ["space-exploration"] = "0.6.108",
  ["space-exploration-graphics"] = "0.6.15",
  ["space-exploration-graphics-2"] = "0.6.1",
  ["space-exploration-graphics-3"] = "0.6.2",
  ["space-exploration-graphics-4"] = "0.6.2",
  ["space-exploration-graphics-5"] = "0.6.1",
  ["space-exploration-menu-simulations"] = "0.6.8",
  ["space-exploration-postprocess"] = "0.6.26",
  textplates = "0.6.10",
  ["weapon-bandoleer"] = "1.0.6"
}

**Comment by mrozpara** [comment]
what kind of error message are you getting? 
Can you please share 2 files:
- errorExporting.json
- errorlog.txt

**Comment by jame2312** [comment]
I cant seem to add the .json files.
![Capture](https://github.com/DanielKote/Foreman2/assets/75223315/36bf1824-f83a-4177-a297-5d43da05b006)
[errorlog.txt](https://github.com/DanielKote/Foreman2/files/11616151/errorlog.txt)

**Comment by jame2312** [comment]
I can't put a .Json file here so I made it a .txt file. let me know if this works or if I need to try Sumthing else.
[errorExporting.txt](https://github.com/DanielKote/Foreman2/files/11616320/errorExporting.txt)

**Comment by DanielKote** [comment]
Seems like the issue is with SE - this is the error code from above:

`4.683 Error Util.cpp:83: Error while loading entity prototype "se-gate-fragment-14-a" (simple-entity): Sprite height outside valid range (1-2048).`
`At ROOT.simple-entity.se-gate-fragment-14-a.picture.layers[0].hr_version
Modifications: Space Exploration â€ºÂ Combat Mechanics Overhaul`
`------------- Error -------------`
`Error while loading entity prototype "se-gate-fragment-14-a" (simple-entity): Sprite height outside valid range (1-2048).`
`At ROOT.simple-entity.se-gate-fragment-14-a.picture.layers[0].hr_version
Modifications: Space Exploration â€ºÂ Combat Mechanics Overhaul`

I tried searching for options which lead to the reddit post [here](https://www.reddit.com/r/factorio/comments/nz8cba/need_help_with_a_factorio_dedicated_server_error/).

The answer apparently is to change graphics-quality in the config/config.ini file to normal.

Try that and see if it helps?

**Comment by jame2312** [comment]
that did seem to work thanks for the help.
